Position section
webstudio-is/webstudio-builder pull request #1879
Opened 2023-06-29 21:29 UTC by istarkov

## Description

1. What is this PR about (link the issue and add a short description)

## Steps for reproduction

1. click button
2. expect xyz

## Code Review

- [ ] hi @kof, I need you to do
  - conceptual review (architecture, feature-correctness)
  - detailed review (read every line)
  - test it on preview

## Before requesting a review

- [ ] made a self-review
- [ ] added inline comments where things may be not obvious (the "why", not "what")

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-builder/blob/main/apps/builder/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `builder/env-check.js` if mandatory

2023-07-09 14:30 UTC, kof commented
> Changed label fonts on fonts from design. IMO non monospaced fonts for numeric dynamic labels is disaster.

Is the new font used non-monospaced? Was this problem discussed?

2023-07-09 14:31 UTC, istarkov commented
Yep, wrote in discord

2023-07-09 14:32 UTC, kof commented
- [ ] position when set is showed with ellipsis - I bet it was either unexpected in design or something is wrong with implementation, we def. need to get rid of ellipsis there

2023-07-09 14:33 UTC, kof commented
Question: is this look expected @taylornowotny ?

<img width="127" alt="Screenshot 2023-07-09 at 16 33 07" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/43a66e09-afac-43f9-b625-86489e882426">

2023-07-09 14:35 UTC, istarkov commented
Label has ellipsis for cases where it doesnt fit. I wrote in discord that current design with changes on 1-2px cause unpredictable effects, especially having that some css/html rendering a little bit different from figma

2023-07-09 14:36 UTC, istarkov commented
Label has ellipsis for cases where it doesnt fit. I wrote in discord that current design with changes on 1-2px cause unpredictable effects, especially having that some css/html rendering a little bit different from figma

2023-07-09 14:36 UTC, kof commented
- [ ] probably out of scope here, but still it would be much nicer if we could start dragging scrub on "Auto" or anything else when there is a unit value possible, and it would just switch to a number and start changing it just like you did it with position. It's nice when position says Auto but I don't need to set 0 before I can start using scrub

2023-07-09 14:45 UTC, kof commented
- [ ] If user selects static and changes top/left/right/bottom and doesn't see any effect they will be confused. Same for other values that don't allow for offset positioning. What did we define for this in figma?

2023-07-09 14:45 UTC, kof requested changes
tested, haven't read code yet, todos in comments

2023-07-09 14:48 UTC, kof commented
@taylornowotny sounds like design needs adjustments

2023-07-09 17:29 UTC, istarkov commented
> Question: is this look expected @taylornowotny ?
> 
> <img alt="Screenshot 2023-07-09 at 16 33 07" width="127" src="https://user-images.githubusercontent.com/52824/252151516-43a66e09-afac-43f9-b625-86489e882426.png">

<img width="232" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5077042/d81fdcc9-1816-488f-8d59-ea0e46f83e52">

The issue that font has different width's fo symbols, and for example for 111 it would fit, but internally I use width for `333` otherwise during scrub it starts jumps from 2 line to 3 line
We need control to be at least 10-20px wider to fit at least {xxx}px

2023-07-09 17:40 UTC, istarkov commented
> * [ ]  If user selects static and changes top/left/right/bottom and doesn't see any effect they will be confused. Same for other values that don't allow for offset positioning. What did we define for this in figma?

In design initial appearance is 
<img width="217" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5077042/d2762682-ffc6-4d31-a8d2-6331d5b3c977">

The issue and why I did like now is that zIndex can be set on static elements, but by design zIndex is going with position section.

2023-07-09 18:19 UTC, kof commented
@istarkov so what needs to be done?

2023-07-09 18:21 UTC, istarkov commented
https://discord.com/channels/955905230107738152/1048308525673238558/1127655984416948354

2023-07-09 20:09 UTC, TrySound commented on apps/builder/app/builder/features/style-panel/sections/shared/keyboard.ts
> +// import type { SpaceStyleProperty } from "./types";
remove comment?

2023-07-09 20:11 UTC, TrySound approved these changes

2023-07-11 20:55 UTC, kof approved these changes

2023-07-11 21:29 UTC, merged